#!/bin/bash


progname=$(basename $0)

usage() {
  if [ $# -ne 0 ]; then
    echo "$progname: $*"
  fi
  echo "usage: $progname [-sscale] [infile [outfile]]"
  exit 2
}


nupOpts=

while getopts s: opt; do
  case $opt in
    s)
      nupOpts=$nupOpts" -s$OPTARG"
      ;;
  esac
done

shift $(( $OPTIND - 1 ))


if [  $# -gt 2 ]; then
  usage "too many arguments ($#)"
fi


if [ $# -ge 1 ]; then
  infile="$1"
else
  infile=-
fi

cat "$infile" | \
 psbook | psnup -2 $nupOpts | pstops 2:0,1U\(1w,1h\) |

if [ $# -ge 2 ]; then
  # Copy shell standard input to a file.
  cat > "$2"
else
  # Copy shell standard input to standard output.
  cat
fi
