#!/usr/bin/bash

dest=$1
days=${2-1}

user=joelsu

if [ x"$dest" == x"" ]; then
    echo "usage err"
    echo "usage: cplogs dest-dir [days-old]"
    echo "       dest-dir should be on the local machine, e.g., /var/tmp/logs"
    exit
fi

# -e = exit if any command fails
# -x = echo each command as executed
set -ex

#cd /var/opt/SUNWSMS/adm
mkdir -p $dest
find . -mtime -$days | cpio -pdu -R$user $dest
chown -R $user $dest
chmod -R a+rX $dest
