#!/bin/bash

cat <<'_EOF_'

bash
cd /workspace/joelsu/esms   # my workspace dir
sh src/tools/esmsws $PWD

cd src
gmake install        # builds production code and test code

gmake tests          # a way to run all unit tests on BUILD SERVERS only

../tests/bin/jrun  # a way to run any unit tests on SIMICS/linux/etc.

cd $CODEMGR_WS/src/java; ant install style

_EOF_

rlogin sanpen-cs10-0
