#!/bin/bash

killflag=

while getopts 9ks: opt
do
  case $opt in
    9)
      killflag=1
      signal=KILL;;
    k)
      killflag=1
      signal=TERM;;
    s)
      killflag=1
      signal="$OPTARG";;
  esac
done

shift $(($OPTIND - 1))

ps -e -o user,pid,ppid,stime,tty,time,comm | egrep "  USER|[ /]$1\$"

if [ -n "$killflag" ]
then
  pids=`ps -e -o pid,comm | grep "[ /]$1\$" | awk '{ print $1 }'`
  if [ -n "$pids" ]
  then
    kill -s "$signal" -- $pids
  fi
  echo "Killed `echo $pids | wc -w | awk '{ print $1 }'` processes."
fi
