#!/bin/bash

# indirs -- given a list of files, cd into each file's directory and run a
# command.


progname=$(basename $0)

usage() {
    if [ $# -ne 0 ]; then
        echo "$progname: $*"
    fi
    echo "usage: $progname command \; file..."
    echo "(example: $progname sccs edit \; \$(find . -name Makefile))"
    exit 2
}


# nupOpts=

# while getopts s: opt; do
#     case $opt in
#         s)
#             nupOpts=$nupOpts" -s$OPTARG"
#             ;;
#     esac
# done

# shift $(( $OPTIND - 1 )


i=0
while [ $# != 0 -a "x$1" != "x;" ]; do
    cmd[$i]="$1"
    i=$(($i + 1))
    shift
done
if [ $# == 0 ]; then
    usage
fi
shift

if [ $# == 0 ]; then
    usage "no files specified"
fi

tmpfile="/tmp/$progname-$$"

origdir=$(pwd)
for path in "$@"; do
    dir=$(dirname "$path")
    file=$(basename "$path")

    echo "$path"
    cd "$dir"
    "${cmd[@]}" "$file"
    cd "$origdir"
    echo
done

# Local Variables:
# indent-tabs-mode: nil
# End:
