#!/bin/bash

SRC=/workspace/joelsu/mygate/src/misc
DEST=/workspace/sms-sust/pub/bin

# restore15k is a symlink to restore15k.0, .1, or .2
# same for restore15k_bringup

# when we install a new version, replace the oldest version and update the
# symlinks to point to it.

r15klink=$DEST/restore15k

if ls -l $r15klink | grep 'k\.0'; then
    suf=1
elif ls -l $r15klink | grep 'k\.1'; then
    suf=2
elif ls -l $r15klink | grep 'k\.2'; then
    suf=0
else
    echo "cannot determine suffix"
    exit 1
fi


set -e  # exit on error

for file in restore15k restore15k_bringup; do
    if [ ! -e $SRC/$file ]; then
        echo "missing file: $file"
        exit 1
    fi

    # should never have a tab followed by a space
    if grep "	 " $SRC/$file /dev/null; then
        echo "bad indentation found in $file"
        exit 1
    fi
done

cd $DEST

for file in restore15k restore15k_bringup; do
    cp $SRC/$file $file.$suf
    ln -s $file.$suf $file
done
