#!/bin/bash

USAGE="$0 [-p] [-t tabwidth] [files...]"

tabwidth=8
printline=0

while getopts pt: opt; do
  case $opt in
    p)
      printline=1
      ;;
    t)
      if [ "$OPTARG" -gt 0 ] > /dev/null; then
        tabwidth="$OPTARG"
      else
        echo "$0: invalid tab width -- $OPTARG"
        echo $USAGE
        exit 2
      fi
      ;;
    \?) 
      echo $USAGE
      exit 2
      ;;
  esac
done

shift $(($OPTIND - 1))

if [ $printline != 0 ]; then
  awkprog='{printf "%3d: %s\n", length($0), $0}'
else
  awkprog='{printf "%3d\n", length($0)}'
fi

if [ "x$*" == "x" ]; then 
  cat | expand -$tabwidth | awk "$awkprog" | sort -nr | head -1
else
  for file in $*; do
    if [ "x$file" == "x-" -o -r "$file" ]; then
      printf "%20s: " "$file"
      cat $file | expand -$tabwidth | awk "$awkprog" | sort -nr | head -1
    else
      echo "$file: unreadable"
    fi
  done
fi
