#!/bin/bash

usage() {
	if [ $# -ne 0 ]; then
		echo "$progname: $*"
	fi
	echo "usage: $progname termname"
	exit 2
}

if [ $# -lt 1 ]; then
	usage
fi
name=$1
shift

if [ ! -d ~/l -o -e ~/l/"$name" -o ! -w ~/l ]; then
	echo "file error"
	exit 2
fi

xterm -n "$name" -lf "/home/joelsu/l/$name" -l "$@" &
