#!/bin/bash

# Create a tar file containing Python utilities: the FLOOT and ULIB. This
# script must be run in an SMS Test workspace directory. (For example,
# /dhpg/test/gate/smstest.)


prog=$(basename $0)

usage() {
	echo "usage: $prog tarfile"
	exit 2
}

die() {
	if [ $# != 0 ]; then
		echo "$prog: $*"
##		format="$1"
##		shift
##		printf "$prog: $format\n" "$@"
	fi
	exit 2
}


if [ $# != 1 ]; then
	usage
fi
tarfile=$1

if [[ ! -r src/ulib-py || ! -r src/floot-py ]]; then
	die "working directory does not appear to be an SMS Test workspace"
fi

tmpdir=/tmp/py-tar$$
wsdir=$PWD

# ** -e: TOLERATE NO ERRORS **
set -e

mkdir $tmpdir

for pkg in ulib floot; do
	mkdir $tmpdir/$pkg
	cp src/$pkg-py/*.py $tmpdir/$pkg
	cd $tmpdir/$pkg
	for mod in *.py; do
		chmod 644 $mod
		echo "compiling module: $pkg/$mod"
		python -c "import py_compile; py_compile.compile('$mod')"
	done
	cd $wsdir
done

cd $tmpdir
tar cpf tar-file *
cd $wsdir
mv $tmpdir/tar-file $tarfile
echo "created $tarfile"

rm -r $tmpdir
