#!/bin/bash

progname=$(basename $0)

usage() {
  if [ $# -ne 0 ]; then
    echo "$progname: $*"
  fi
  echo "usage: $progname filename..."
  exit 2
}

if [ $# -gt 0 ]; then
  usage "too many arguments ($#)"
fi

echo $PATH | tr ":" "\n" |
while read dir; do
##  mountinfo=$(df -k "$dir" | sed 's".*(""' | sed 's"[ /].*""')
  mountinfo="$(expr "$(df "$dir")" : '.*(\([^)]*:\).*')"
  printf "%-15s %s\n" "$(basename "$mountinfo")" "$dir"
done
