#!/bin/bash

# filter -- run a bunch of files through a filter; output overwrites the
# original files.

progname=$(basename $0)

usage() {
  echo "usage: $progname sccs-controlled-file"
  exit 2
}

if [ $# -ne 1 ]; then
    usage
fi

# Algorithm:
# 1. Construct a temporary sed script from the sccs revision history
#    The script has one line for each revision in the history
# 2. Run "sccs get -mps" and pipe the output to the sed script
# 3. Delete the sed script

sedScript=/tmp/$$.sed
srcFile="$1"
IFS=" "  # controls "read"

# Construct a temporary sed script from the sccs revision history
sccs prs -r1.1 -l -d ":I: :P:" $srcFile | \
while read revision user; do
    printf "s/^%s\t/%-9s %9s  /g\n" $revision $revision $user
done > $sedScript

[ $? -eq 0 ] || exit $?

sccs get -mps $srcFile | sed -f $sedScript

rm $sedScript
