#! /usr/bin/bash
usage()
{
	echo "usage: $0 userid"
	exit 1
}

if [ $# -ne 1 ]
then
	usage
fi


# set up proper priviledges for the user 

/opt/SUNWSMS/bin/smsconfig -a -u $1 -G admn platform
for i in a b c d e f g h i j k l m n o p q r
do
	/opt/SUNWSMS/bin/smsconfig -a -u $1 -G admn $i
done
