#! /usr/bin/env python

import sys
import os
import stat
import time

name = sys.argv[1]

s = os.stat(name)
print "CTIME: ", time.asctime(time.localtime(s[stat.ST_CTIME]))
print "MTIME: ", time.asctime(time.localtime(s[stat.ST_MTIME]))
print "ATIME: ", time.asctime(time.localtime(s[stat.ST_ATIME]))
