#!/usr/bin/env python

import sys
import string

inf = sys.stdin
outf = sys.stdout

outf.write("""CD_DA
""")

fnameDict = {}

trackNum = 1
lines = inf.readlines()[1:]
for line in lines:
    if string.lstrip(line) == "":
	continue
    if line[-1:] == "\n":
	line = line[:-1]
    pregap = int(string.split(line, " ", 1)[0])
    origFname = string.split(line, "/")[-1]
    fname = string.replace(origFname, ".mp3", ".wav")
    if fnameDict.has_key(fname):
	sys.stderr.write("filename collision!\n")
	sys.exit(2)
    fnameDict[fname] = None
    if pregap == 0:
        outf.write('''
// Track %d
TRACK AUDIO
FILE "%s" 0 
''' % (trackNum, fname))
    else:
        outf.write('''
// Track %d
TRACK AUDIO
PREGAP 00:%02d:00
FILE "%s" 0 
''' % (trackNum, pregap, fname))

    trackNum = trackNum + 1
